name: Main

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: docker-compose --file docker-compose.ci.yml run ci
      - name: 'see'
        run: ls
      - name: 'see'
        run: ls coverage -la
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          parallel: false